export default {
  // Docs
  docs: '/',
  docsHome: '/introduction',
  docsAi: '/ai/ai-intro',
  api: '/reference/api-reference',
  auth: '/guides/gibson-auth',
  autoscaling: '/introduction/autoscaling',
  billing: '/introduction/about-billing',
  branchRestore: '/introduction/branch-restore',
  changelog: '/changelog',
  cliInstall: '/reference/cli-install',
  cliReference: '/reference/gibson-cli',
  connectionPooling: '/connect/connection-pooling',
  docsBranching: '/introduction/branching',
  docsMigration: '/import/import-data-assistant',
  manageBilling: '/introduction/manage-billing',
  pgSearch: '/extensions/pg_search',
  rlsAuthorize: '/guides/gibson-rls',
  serverless: '/introduction/serverless',
  support: '/introduction/support',
  hipaaCompliance: '/security/hipaa',
  // Socials
  discord: 'https://www.gibsonai.com/discord',
  github: 'https://github.com/GibsonAI/',
  twitter: 'https://x.com/heygibsonai',
};
